Suraj
Hackodisha/Hackodisha2023 pull request #27
Opened 2023-07-07 18:02 UTC by Skb08

**Description**

This PR fixes #11 

**Notes for Reviewers**

2023-07-08 02:49 UTC, duckling69 approved these changes
please just change names of css classes to be more specific and remove unwanted comments if we don't need them 
LGTM apart from that good work 👏

2023-07-08 15:09 UTC, 8rxn requested changes
@Skb08 Please Make these minor changes and it'll be ready to merge.

2023-07-08 15:09 UTC, 8rxn commented on src/app/page.js
> +      <div className="flex min-h-screen min-w-screen flex-col items-center  xl:p-0 md:text-2xl bg-black shadow"  >
Needs a little more padding from top and takes up height more than it needs
![image](https://github.com/Hackodisha/Hackodisha2023/assets/75237697/45d8f5fe-cc3a-46c2-b932-29ffa0c28b62)

2023-07-08 15:09 UTC, 8rxn commented on src/app/suraj/Statistics.js
> +const Statistics = () => {
Move this file into the appropriate folder as informed in group chat.

2023-07-08 15:09 UTC, 8rxn commented on public/Images/base.svg
Use relevant filenames instead of vague ones like "base". Also prepend them with their target component: Sponsor here.

2023-07-09 16:20 UTC, duckling69 commented
Thanks @Skb08 @8rxn 👏

2023-07-09 16:20 UTC, merged